# Generated by Django 3.1.7 on 2021-03-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210330_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/class_background'),
        ),
    ]
