# Generated by Django 3.1.7 on 2021-03-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_homework_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='background',
        ),
        migrations.AddField(
            model_name='room',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/class_background'),
        ),
    ]
